### ISSUE TITLE
Reflective Screens span across entire body?

### ISSUE THREAD

**Issue by foxotic** [PiMaker/ltcgi#34]
![image](https://github.com/user-attachments/assets/81d50d56-63b9-4927-aa3c-9dae7f012a42)
I'm not versed in shaders, but I was wondering if there is a way to distribute the reflections different? Currently, each piece of the armor shown will reflect the ltcgi source as well as the visor. I would think the reflections across the armor would be a little more uniform and have the same video span across the whole body. Can I get some guidance toward how I may be able to set that up?

**Comment by PiMaker** [comment]
LTC approximates real light behaviour, so for a shiny surface this is how it would look in real life. To spread it out more, you need to use the "Smoothness" or "Roughness" parameter of your material. There's no way to directly "spread out the reflection", because that's not how light works in real life either.
In general, these types of question may be a better fit for my [discord server](https://discord.gg/r38vJd2DuJ), so I will be closing this issue.
